//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.13 at 01:30:26 PM CET 
//


package de.vdv.ojp;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import de.vdv.ojp.model.AirSubmodesOfTransportEnumeration;
import de.vdv.ojp.model.BusSubmodesOfTransportEnumeration;
import de.vdv.ojp.model.CoachSubmodesOfTransportEnumeration;
import de.vdv.ojp.model.FunicularSubmodesOfTransportEnumeration;
import de.vdv.ojp.model.MetroSubmodesOfTransportEnumeration;
import de.vdv.ojp.model.RailSubmodesOfTransportEnumeration;
import de.vdv.ojp.model.TelecabinSubmodesOfTransportEnumeration;
import de.vdv.ojp.model.TramSubmodesOfTransportEnumeration;
import de.vdv.ojp.model.VehicleModesOfTransportEnumeration;
import de.vdv.ojp.model.WaterSubmodesOfTransportEnumeration;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.rutebanken.netex.OmitNullsToStringStyle;


/**
 * List of public transport modes ([from SIRI] mode of public transport service, corresponds to VEHICLE MODE) to include or exclude.
 * 
 * <p>Java class for PtModeFilterStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PtModeFilterStructure"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Exclude" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="PtMode" type="{http://www.siri.org.uk/siri}VehicleModesOfTransportEnumeration" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;group ref="{http://www.siri.org.uk/siri}PtModeChoiceGroup" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PtModeFilterStructure", propOrder = {
    "exclude",
    "ptMode",
    "ptModeChoiceGroup"
})
public class PtModeFilterStructure {

    @XmlElement(name = "Exclude", defaultValue = "true")
    protected Boolean exclude;
    @XmlElement(name = "PtMode")
    @XmlSchemaType(name = "NMTOKEN")
    protected List<VehicleModesOfTransportEnumeration> ptMode;
    @XmlElements({
        @XmlElement(name = "AirSubmode", namespace = "http://www.siri.org.uk/siri", type = AirSubmodesOfTransportEnumeration.class, defaultValue = "unknown"),
        @XmlElement(name = "BusSubmode", namespace = "http://www.siri.org.uk/siri", type = BusSubmodesOfTransportEnumeration.class, defaultValue = "unknown"),
        @XmlElement(name = "CoachSubmode", namespace = "http://www.siri.org.uk/siri", type = CoachSubmodesOfTransportEnumeration.class, defaultValue = "unknown"),
        @XmlElement(name = "FunicularSubmode", namespace = "http://www.siri.org.uk/siri", type = FunicularSubmodesOfTransportEnumeration.class, defaultValue = "unknown"),
        @XmlElement(name = "MetroSubmode", namespace = "http://www.siri.org.uk/siri", type = MetroSubmodesOfTransportEnumeration.class, defaultValue = "unknown"),
        @XmlElement(name = "TramSubmode", namespace = "http://www.siri.org.uk/siri", type = TramSubmodesOfTransportEnumeration.class, defaultValue = "unknown"),
        @XmlElement(name = "TelecabinSubmode", namespace = "http://www.siri.org.uk/siri", type = TelecabinSubmodesOfTransportEnumeration.class, defaultValue = "unknown"),
        @XmlElement(name = "RailSubmode", namespace = "http://www.siri.org.uk/siri", type = RailSubmodesOfTransportEnumeration.class, defaultValue = "unknown"),
        @XmlElement(name = "WaterSubmode", namespace = "http://www.siri.org.uk/siri", type = WaterSubmodesOfTransportEnumeration.class, defaultValue = "unknown")
    })
    protected List<Object> ptModeChoiceGroup;

    /**
     * Gets the value of the exclude property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExclude() {
        return exclude;
    }

    /**
     * Sets the value of the exclude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExclude(Boolean value) {
        this.exclude = value;
    }

    /**
     * Gets the value of the ptMode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ptMode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPtMode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VehicleModesOfTransportEnumeration }
     * 
     * 
     */
    public List<VehicleModesOfTransportEnumeration> getPtMode() {
        if (ptMode == null) {
            ptMode = new ArrayList<VehicleModesOfTransportEnumeration>();
        }
        return this.ptMode;
    }

    /**
     * Gets the value of the ptModeChoiceGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ptModeChoiceGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPtModeChoiceGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AirSubmodesOfTransportEnumeration }
     * {@link BusSubmodesOfTransportEnumeration }
     * {@link CoachSubmodesOfTransportEnumeration }
     * {@link FunicularSubmodesOfTransportEnumeration }
     * {@link MetroSubmodesOfTransportEnumeration }
     * {@link TramSubmodesOfTransportEnumeration }
     * {@link TelecabinSubmodesOfTransportEnumeration }
     * {@link RailSubmodesOfTransportEnumeration }
     * {@link WaterSubmodesOfTransportEnumeration }
     * 
     * 
     */
    public List<Object> getPtModeChoiceGroup() {
        if (ptModeChoiceGroup == null) {
            ptModeChoiceGroup = new ArrayList<Object>();
        }
        return this.ptModeChoiceGroup;
    }

    public PtModeFilterStructure withExclude(Boolean value) {
        setExclude(value);
        return this;
    }

    public PtModeFilterStructure withPtMode(VehicleModesOfTransportEnumeration... values) {
        if (values!= null) {
            for (VehicleModesOfTransportEnumeration value: values) {
                getPtMode().add(value);
            }
        }
        return this;
    }

    public PtModeFilterStructure withPtMode(Collection<VehicleModesOfTransportEnumeration> values) {
        if (values!= null) {
            getPtMode().addAll(values);
        }
        return this;
    }

    public PtModeFilterStructure withPtModeChoiceGroup(Object... values) {
        if (values!= null) {
            for (Object value: values) {
                getPtModeChoiceGroup().add(value);
            }
        }
        return this;
    }

    public PtModeFilterStructure withPtModeChoiceGroup(Collection<Object> values) {
        if (values!= null) {
            getPtModeChoiceGroup().addAll(values);
        }
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, OmitNullsToStringStyle.INSTANCE);
    }

}
