//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.13 at 01:30:26 PM CET 
//


package de.vdv.ojp;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import de.vdv.ojp.model.LocationStructure;
import de.vdv.ojp.model.ProgressBetweenStopsStructure;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.rutebanken.netex.OmitNullsToStringStyle;


/**
 * Geographical and logical position of a vehicle.
 * 
 * <p>Java class for VehiclePositionStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehiclePositionStructure"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GeoPosition" type="{http://www.siri.org.uk/siri}LocationStructure" minOccurs="0"/&gt;
 *         &lt;element name="Progress" type="{http://www.vdv.de/ojp}VehicleProgressEnumeration" minOccurs="0"/&gt;
 *         &lt;element name="Bearing" type="{http://www.siri.org.uk/siri}AbsoluteBearingType" minOccurs="0"/&gt;
 *         &lt;element name="ProgressBetweenStops" type="{http://www.siri.org.uk/siri}ProgressBetweenStopsStructure" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehiclePositionStructure", propOrder = {
    "geoPosition",
    "progress",
    "bearing",
    "progressBetweenStops"
})
public class VehiclePositionStructure {

    @XmlElement(name = "GeoPosition")
    protected LocationStructure geoPosition;
    @XmlElement(name = "Progress")
    @XmlSchemaType(name = "string")
    protected VehicleProgressEnumeration progress;
    @XmlElement(name = "Bearing")
    protected Float bearing;
    @XmlElement(name = "ProgressBetweenStops")
    protected ProgressBetweenStopsStructure progressBetweenStops;

    /**
     * Gets the value of the geoPosition property.
     * 
     * @return
     *     possible object is
     *     {@link LocationStructure }
     *     
     */
    public LocationStructure getGeoPosition() {
        return geoPosition;
    }

    /**
     * Sets the value of the geoPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationStructure }
     *     
     */
    public void setGeoPosition(LocationStructure value) {
        this.geoPosition = value;
    }

    /**
     * Gets the value of the progress property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleProgressEnumeration }
     *     
     */
    public VehicleProgressEnumeration getProgress() {
        return progress;
    }

    /**
     * Sets the value of the progress property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleProgressEnumeration }
     *     
     */
    public void setProgress(VehicleProgressEnumeration value) {
        this.progress = value;
    }

    /**
     * Gets the value of the bearing property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getBearing() {
        return bearing;
    }

    /**
     * Sets the value of the bearing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setBearing(Float value) {
        this.bearing = value;
    }

    /**
     * Gets the value of the progressBetweenStops property.
     * 
     * @return
     *     possible object is
     *     {@link ProgressBetweenStopsStructure }
     *     
     */
    public ProgressBetweenStopsStructure getProgressBetweenStops() {
        return progressBetweenStops;
    }

    /**
     * Sets the value of the progressBetweenStops property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgressBetweenStopsStructure }
     *     
     */
    public void setProgressBetweenStops(ProgressBetweenStopsStructure value) {
        this.progressBetweenStops = value;
    }

    public VehiclePositionStructure withGeoPosition(LocationStructure value) {
        setGeoPosition(value);
        return this;
    }

    public VehiclePositionStructure withProgress(VehicleProgressEnumeration value) {
        setProgress(value);
        return this;
    }

    public VehiclePositionStructure withBearing(Float value) {
        setBearing(value);
        return this;
    }

    public VehiclePositionStructure withProgressBetweenStops(ProgressBetweenStopsStructure value) {
        setProgressBetweenStops(value);
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, OmitNullsToStringStyle.INSTANCE);
    }

}
