//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.13 at 01:30:26 PM CET 
//


package de.vdv.ojp.model;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.rutebanken.netex.OmitNullsToStringStyle;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{http://www.siri.org.uk/siri}OJPRequest"/&gt;
 *           &lt;element ref="{http://www.siri.org.uk/siri}OJPResponse"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{http://www.siri.org.uk/siri}Extensions" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" fixed="1.0" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ojpRequest",
    "ojpResponse",
    "extensions"
})
@XmlRootElement(name = "OJP")
public class OJP {

    @XmlElement(name = "OJPRequest")
    protected OJPRequestStructure ojpRequest;
    @XmlElement(name = "OJPResponse")
    protected OJPResponseStructure ojpResponse;
    @XmlElement(name = "Extensions")
    protected ExtensionsStructure extensions;
    @XmlAttribute(name = "version", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String version;

    /**
     * Gets the value of the ojpRequest property.
     * 
     * @return
     *     possible object is
     *     {@link OJPRequestStructure }
     *     
     */
    public OJPRequestStructure getOJPRequest() {
        return ojpRequest;
    }

    /**
     * Sets the value of the ojpRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link OJPRequestStructure }
     *     
     */
    public void setOJPRequest(OJPRequestStructure value) {
        this.ojpRequest = value;
    }

    /**
     * Gets the value of the ojpResponse property.
     * 
     * @return
     *     possible object is
     *     {@link OJPResponseStructure }
     *     
     */
    public OJPResponseStructure getOJPResponse() {
        return ojpResponse;
    }

    /**
     * Sets the value of the ojpResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link OJPResponseStructure }
     *     
     */
    public void setOJPResponse(OJPResponseStructure value) {
        this.ojpResponse = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionsStructure }
     *     
     */
    public ExtensionsStructure getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionsStructure }
     *     
     */
    public void setExtensions(ExtensionsStructure value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    public OJP withOJPRequest(OJPRequestStructure value) {
        setOJPRequest(value);
        return this;
    }

    public OJP withOJPResponse(OJPResponseStructure value) {
        setOJPResponse(value);
        return this;
    }

    public OJP withExtensions(ExtensionsStructure value) {
        setExtensions(value);
        return this;
    }

    public OJP withVersion(String value) {
        setVersion(value);
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, OmitNullsToStringStyle.INSTANCE);
    }

}
